export * from './acervo'
export * from './navBar'
export * from './Principal'
export * from './login'
export * from './cadastroUsuario'
export * from './detalhes'
export * from './cadastrarPatrimonio'
