export * from './acervo'
export * from './navBar'
export * from './principal'
export * from './login'
export * from './cadastroUsuario'
export * from './detalhes'
export * from './titlebar'
export * from './cadastrarPatrimonio'
